In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\vibha\Downloads\super store data set\SampleSuperstore.csv")

In [4]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [5]:
df.head(10)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
5,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,48.8600,7,0.00,14.1694
6,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,7.2800,4,0.00,1.9656
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.1520,6,0.20,90.7152
8,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,18.5040,3,0.20,5.7825
9,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,114.9000,5,0.00,34.4700

In [6]:
df.tail()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.248,3,0.2,4.1028
9990,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.960,2,0.0,15.6332
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.576,2,0.2,19.3932
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.600,4,0.0,13.3200
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.160,2,0.0,72.9480

In [7]:
df.tail(20)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
9974,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Office Supplies,Art,18.690,7,0.0,5.2332
9975,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Office Supplies,Paper,13.360,2,0.0,6.4128
9976,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Technology,Phones,249.584,2,0.2,31.1980
9977,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Office Supplies,Fasteners,13.860,7,0.0,0.0000
9978,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Office Supplies,Binders,13.376,4,0.2,4.6816
9979,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Office Supplies,Binders,437.472,14,0.2,153.1152
9980,Second Class,Consumer,United States,Lafayette,Louisiana,70506,South,Furniture,Tables,84.980,1,0.0,22.3548
9981,First Class,Consumer,United States,Fairfield,Ohio,45014,East,Office Supplies,Labels,16.520,5,0.2,5.3690
9982,Standard Class,Consumer,United States,Grand Rapids,Michigan,49505,Central,Office Supplies,Paper,35.560,7,0.0,16.7132
9983,Standard Class,Consumer,United States,Grand Rapids,Michigan,49505,Central,Technology,Phones,97.980,2,0.0,25.4344
9984,Standard Class,Consumer,United States,Long Beach,New York,11561,East,Office Supplies,Labels,31.500,10,0.0,15.1200
9985,Standard Class,Consumer,United States,Long Beach,New York,11561,East,Office Supplies,Supplies,55.600,4,0.0,16.1240
9986,Standard Class,Consumer,United States,Los Angeles,California,90008,West,Technology,Accessories,36.240,1,0.0,14.2500
9987,Standard Class,Corporate,United States,Athens,Georgia,30605,South,Technology,Accessories,79.990,1,0.0,28.7964
9988,Standard Class,Corporate,United States,Athens,Georgia,30605,South,Technology,Phones,206.100,5,0.0,55.6470
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.248,3,0.2,4.1028
9990,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.960,2,0.0,15.6332
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.576,2,0.2,19.3932
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.600,4,0.0,13.3200
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.160,2,0.0,72.9480

In [8]:
df.sample()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
9566,Same Day,Consumer,United States,Tampa,Florida,33614,South,Office Supplies,Binders,12.645,5,0.7,-10.116

In [9]:
df.sample(20)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
6820,Standard Class,Corporate,United States,Peoria,Illinois,61604,Central,Furniture,Chairs,113.372,2,0.3,-3.2392
1470,Standard Class,Corporate,United States,Detroit,Michigan,48234,Central,Office Supplies,Paper,12.960,2,0.0,6.2208
226,Standard Class,Corporate,United States,Detroit,Michigan,48227,Central,Furniture,Tables,622.450,5,0.0,136.9390
4498,Standard Class,Corporate,United States,San Francisco,California,94110,West,Office Supplies,Paper,12.960,2,0.0,6.2208
463,Standard Class,Home Office,United States,Phoenix,Arizona,85023,West,Furniture,Tables,1272.630,6,0.5,-814.4832
35,First Class,Corporate,United States,Richardson,Texas,75080,Central,Technology,Phones,1097.544,7,0.2,123.4737
9377,Standard Class,Corporate,United States,Eau Claire,Wisconsin,54703,Central,Office Supplies,Storage,32.560,2,0.0,8.4656
1508,Same Day,Home Office,United States,Omaha,Nebraska,68104,Central,Office Supplies,Binders,34.500,3,0.0,15.5250
3733,Standard Class,Corporate,United States,Clinton,Maryland,20735,East,Office Supplies,Binders,65.080,4,0.0,31.8892
2451,Second Class,Consumer,United States,New York City,New York,10011,East,Technology,Phones,119.700,6,0.0,31.1220
1485,Standard Class,Consumer,United States,New York City,New York,10035,East,Office Supplies,Fasteners,3.760,2,0.0,1.3160
81,Standard Class,Consumer,United States,San Francisco,California,94122,West,Office Supplies,Art,14.900,5,0.0,4.1720
4481,Standard Class,Consumer,United States,Los Angeles,California,90049,West,Office Supplies,Appliances,43.320,2,0.0,14.2956
1554,Standard Class,Corporate,United States,Bellevue,Washington,98006,West,Office Supplies,Art,5.280,3,0.0,1.5312
7789,First Class,Consumer,United States,Chicago,Illinois,60653,Central,Office Supplies,Paper,30.528,8,0.2,9.5400
985,Standard Class,Home Office,United States,Pasadena,Texas,77506,Central,Office Supplies,Envelopes,27.968,4,0.2,9.4392
8789,Standard Class,Consumer,United States,Monroe,North Carolina,28110,South,Furniture,Bookcases,77.728,2,0.2,-3.8864
4697,Same Day,Consumer,United States,Detroit,Michigan,48205,Central,Furniture,Chairs,546.660,9,0.0,136.6650
3895,Standard Class,Home Office,United States,Texarkana,Arkansas,71854,South,Technology,Accessories,48.900,5,0.0,18.0930
5566,Same Day,Home Office,United States,Chicago,Illinois,60610,Central,Office Supplies,Art,29.760,5,0.2,1.8600

In [10]:
df.shape

(9994, 13)

In [15]:
len(df)

9994

In [16]:
df.index

RangeIndex(start=0, stop=9994, step=1)

In [17]:
df.dtypes

Ship Mode        object
Segment          object
Country          object
City             object
State            object
Postal Code       int64
Region           object
Category         object
Sub-Category     object
Sales           float64
Quantity          int64
Discount        float64
Profit          float64
dtype: object

In [18]:
df.axes

[RangeIndex(start=0, stop=9994, step=1),
 Index(['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Postal Code',
        'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount',
        'Profit'],
       dtype='object')]

In [19]:
df.size

129922

In [20]:
df.ndim

2

In [22]:
df.describe()

        Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.857901     3.789574     0.156203    28.656599
std    32063.693350    623.245124     2.225110     0.206452   234.260115
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   object
 1   Segment       9994 non-null   object
 2   Country       9994 non-null   object
 3   City          9994 non-null   object
 4   State         9994 non-null   object
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   object
 7   Category      9994 non-null   object
 8   Sub-Category  9994 non-null   object
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), object(8)
memory usage: 1015.1+ KB

In [27]:
sorted_df = df.sort_values(by="Sales")

In [28]:
sorted_df

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
4101,Standard Class,Consumer,United States,Houston,Texas,77095,Central,Office Supplies,Appliances,0.444,1,0.8,-1.1100
9292,Same Day,Corporate,United States,Waco,Texas,76706,Central,Office Supplies,Binders,0.556,1,0.8,-0.9452
8658,Standard Class,Corporate,United States,Chicago,Illinois,60623,Central,Office Supplies,Binders,0.836,1,0.8,-1.3376
4711,Same Day,Consumer,United States,Philadelphia,Pennsylvania,19120,East,Office Supplies,Binders,0.852,1,0.7,-0.5964
2106,Same Day,Corporate,United States,Mesquite,Texas,75150,Central,Office Supplies,Binders,0.876,1,0.8,-1.4016
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4190,Standard Class,Consumer,United States,Newark,Delaware,19711,East,Technology,Copiers,10499.970,3,0.0,5039.9856
2623,First Class,Home Office,United States,New York City,New York,10024,East,Technology,Copiers,11199.968,4,0.2,3919.9888
8153,First Class,Consumer,United States,Seattle,Washington,98115,West,Technology,Copiers,13999.960,4,0.0,6719.9808
6826,Standard Class,Corporate,United States,Lafayette,Indiana,47905,Central,Technology,Copiers,17499.950,5,0.0,8399.9760
2697,Standard Class,Home Office,United States,Jacksonville,Florida,32216,South,Technology,Machines,22638.480,6,0.5,-1811.0784

In [33]:
sorted_df = df.sort_values(by="Sales",ascending=False)
sorted_df

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
2697,Standard Class,Home Office,United States,Jacksonville,Florida,32216,South,Technology,Machines,22638.480,6,0.5,-1811.0784
6826,Standard Class,Corporate,United States,Lafayette,Indiana,47905,Central,Technology,Copiers,17499.950,5,0.0,8399.9760
8153,First Class,Consumer,United States,Seattle,Washington,98115,West,Technology,Copiers,13999.960,4,0.0,6719.9808
2623,First Class,Home Office,United States,New York City,New York,10024,East,Technology,Copiers,11199.968,4,0.2,3919.9888
4190,Standard Class,Consumer,United States,Newark,Delaware,19711,East,Technology,Copiers,10499.970,3,0.0,5039.9856
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Same Day,Corporate,United States,Mesquite,Texas,75150,Central,Office Supplies,Binders,0.876,1,0.8,-1.4016
4711,Same Day,Consumer,United States,Philadelphia,Pennsylvania,19120,East,Office Supplies,Binders,0.852,1,0.7,-0.5964
8658,Standard Class,Corporate,United States,Chicago,Illinois,60623,Central,Office Supplies,Binders,0.836,1,0.8,-1.3376
9292,Same Day,Corporate,United States,Waco,Texas,76706,Central,Office Supplies,Binders,0.556,1,0.8,-0.9452
4101,Standard Class,Consumer,United States,Houston,Texas,77095,Central,Office Supplies,Appliances,0.444,1,0.8,-1.1100